config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated do
    root to: "host/events#index", as: :authenticated_root
  end
  
  resources :events, module: 'host'
  resources :events do
    resource :like
    resource :comment
    resource :event_registration, only: [:create, :destroy], as: :join
  end
  root to: "host/events#index"
  get "event/:id/details", to: "host/events#details", as: 'details'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :guest, class_name: 'User'
  belongs_to :event

  validates_presence_of :body, :event_id, :guest_id

  after_create_commit :notify_recipient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: 'Notification'

  private

  def notify_recipient
    CommentNotification.with(comment: self, event: event).deliver_later(event.host)
  end

  def cleanup_notifications
    notifications_as_comment.destroy_all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.event_id = @event.id
    if @comment.save
      respond_to do |format|
        # format.turbo_stream { flash.now[:notice] = "Comment was successfully created." }
        format.html { redirect_to events_path }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private

  def comment_params
    params.require(:comment).permit(:event_id, :guest_id, :body)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/views/comments/_form.html.erb
<%= form_with model: Comment.new, url: event_comment_path(event) do |form| %>
  <div class="field mx-1 d-flex">
    <%= form.text_field :body, class: "form-control" %>
    <%= link_to "Cancel", events_path, class: "btn btn--light" %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update Comment.new, "" %>
<%= turbo_stream.prepend "flash", partial: "shared/flash_messages"%>

app/views/comments/new.html.erb
<%= turbo_frame_tag "comment_#{@event.id}" do %>
  <%= render partial: 'form', locals: { event: @event, comment: @comment }%>
<% end %>