config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated do
    root to: "host/events#index", as: :authenticated_root
  end
  
  resources :events, module: 'host'
  resources :events do
    resource :like
    resource :comment
    resource :event_registration, only: [:create, :destroy], as: :join
  end
  root to: "host/events#index"
  get "event/:id/details", to: "host/events#details", as: 'details'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :guest, class_name: 'User'
  belongs_to :event

   after_update_commit -> { broadcast_prepend_later_to(self, locals: { user: current_user, like: self }) }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

  def create
    @like = @event.likes.where(guest_id: current_user.id).first_or_create
    
    respond_to do |format|
      format.html { redirect_to events_path }
    end
  end

  def destroy
    @event.likes.where(guest_id: current_user.id).destroy_all

    respond_to do |format| 
      format.html { redirect_to events_path }
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/views/likes/_like.html.erb
<% if current_user.likes?(event) %>
  <%= turbo_frame_tag "like_#{event.id}" do %>
    <%= button_to event_like_path(event), style: "width: 45px", class: "btn btn-default p-0", method: :delete do %>
      <i class="bi bi-heart"></i>
      <i><%= event.likes.count || 0 %></i>
    <% end %>
  <% end %>
<% else %>
  <%= turbo_frame_tag "like_#{event.id}" do %>
    <%= button_to event_like_path(event), style: "width: 45px", class: "btn btn-default p-0", method: :post do %>
      <i class="bi bi-heart"></i>
      <i><%= event.likes.count || 0 %></i>
    <% end %>
  <% end %>
<% end %>