config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated do
    root to: "host/events#index", as: :authenticated_root
  end
  
  resources :events, module: 'host'
  resources :events do
    resource :like
    resource :comment
    resource :event_registration, only: [:create, :destroy], as: :join
  end
  root to: "host/events#index"
  get "event/:id/details", to: "host/events#details", as: 'details'
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image

  belongs_to :host, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, source: :comments
  has_many :event_registrations, dependent: :destroy
  has_many :users, through: :event_registrations
  
  # after_create_commit { broadcast_prepend_to "events" }
  # after_destroy_commit { broadcast_remove_to "events" }
  # after_destroy_commit -> { broadcast_remove_later_to(self, locals: { user: current_user, event: self }) }

  validates_presence_of :time, :address, :theme, :details, :event_type, :status

  validates_date :start_date, :on_or_after => lambda { Date.current },
  :on_or_after_message => "must be on or after today's date.",
  :invalid_date_message => "is empty"

  validates_date :end_date, :on_or_after => lambda { Date.current },
  :invalid_date_message => "is empty",
  :on_or_after_message => "must be on or after today's date."

  def get_status(date)
    current_date = DateTime.now.strftime('%Y-%m-%d')
    end_date = date.strftime('%Y-%m-%d')
    end_date < current_date ? 'inactive' : 'active'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:details, :edit, :update, :show, :destroy]

  def index
    @events = Event.order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def show
    @comments = @event.comments.limit(4)
    mark_notifications_as_read
  end

  def details
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      respond_to do |format|
        format.html { redirect_to events_path, notice: "An event was successfully created."}
        format.turbo_stream { flash.now[:notice] = "Event was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @event.update(event_params)
      respond_to do |format|
        format.html { redirect_to events_path, notice: "Event successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Event successfully updated."}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @events = Event.all
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: "An event was successfully deleted."}
      format.turbo_stream { flash.now[:notice] = "Event successfully deleted."}
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event)
      .permit(:start_date, :end_date, :time, :address, :theme, :details, :image, :event_type, :status, :user_id)
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read = @event.notifications_as_event.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/controllers/host/events_controller.rb
class Host::EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:details, :edit, :update, :show, :destroy]

  def index
    @events = Event.order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def show
    @comments = @event.comments.limit(4)
    mark_notifications_as_read
  end

  def details
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      respond_to do |format|
        format.html { redirect_to events_path, notice: "An event was successfully created."}
        format.turbo_stream { flash.now[:notice] = "Event was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @event.update(event_params)
      respond_to do |format|
        format.html { redirect_to events_path, notice: "Event successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Event successfully updated."}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @events = Event.all
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: "An event was successfully deleted."}
      format.turbo_stream { flash.now[:notice] = "Event successfully deleted."}
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event)
      .permit(:start_date, :end_date, :time, :address, :theme, :details, :image, :event_type, :status, :host_id)
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read = @event.notifications_as_event.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/views/host/events/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="text-center empty-state__text">
    There are no events yet!
  </p>

  <div class="d-flex justify-content-center">
    <%= link_to "Add an event", new_event_path, class: "btn btn-primary", data: { turbo_frame: dom_id(Event.new) } %>   
  </div>
</div>

app/views/host/events/_event.html.erb
<%= turbo_frame_tag dom_id(event) do%>
  <div class="each-event mb-3">
    <div class="mb-0 event-index-image-wrapper">
      <%= link_to event_path(event), data: { turbo_frame: "_top" } do %>
        <%= image_tag(event.image, class: "author_image w-100") if event.image %>
      <% end %>
    </div>
    <div style="background-color: #ebe9e8" class="p-2">
      <p><strong><%= event.theme %></strong></p>
      <div>
        <div class="mb-2 py-2">
          <div class="mb-2 d-flex">
            <% if event.get_status(event.end_date) == 'active' %>
              <span class="border border-success rounded text-capitalize py-1 px-2"><%= event.get_status(event.end_date) %></span>
            <% else %>
              <span class="border border-danger rounded text-capitalize py-1 px-2"><%= event.get_status(event.end_date) %></span>
            <% end %> 
            <span class="border border-primary rounded text-capitalize px-3 mx-1 d-flex align-items-center"><%= event.event_type %></span> 
            <%= turbo_frame_tag "join_#{event.id}" do%>
              <%= render partial: 'event_registration_button', locals: { event: event }%>
            <% end %>
          </div>
        </div>
        <div id="" class="mb-2 d-flex justify-content-between">          
          <div class="d-flex">
            <%= turbo_frame_tag "like_#{event.id}" do %>
              <%= render partial: 'likes/like', locals: { event: event } %>
            <% end %>
            <%= turbo_frame_tag "comment_#{event.id}" do%>
              <%= link_to new_event_comment_path(event), class: "d-flex pt-0 btn btn-default" do %>
                <i class="bi bi-chat-left"></i>
                <i class="d-inline-block mx-1 pb-1"><%= event.comments.count || 0 %></i>
              <% end %>
            <% end %>
          </div>
          <div class="d-flex">
            <%= link_to edit_event_path(event), class: "px-3 py-0 mx-1 btn btn-default" do %>
              <i class="bi bi-pencil-square"></i>
            <% end %>
            <%= button_to event_path(event), class: "d-flex flex-start h-100 py-0 btn btn-default", method: :delete do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/host/events/_event_detail.html.erb
<div class="p-2 card event-detail mx-auto">
  <div class="theme">
    <p class="mb-0 fs-6 "><%= event.details %></p>
  </div>
  <div class="more-details">
    <div>
      <p class="mb-0 fs-6 ">Start date: <%= event.start_date%> </p>
      <p class="mb-0 fs-6 ">End date: <%= event.end_date %></p>
      <p class="mb-0 fs-6 ">Address: <%= event.address %></p>
    </div>
  </div>
</div>

app/views/host/events/_event_registration_button.html.erb
<%= turbo_frame_tag "join_#{event.id}" do%>
  <%= button_to "Join", event_join_path(event), class: "py-1 px-2 btn btn-primary" %>
<% end %>

app/views/host/events/_form.html.erb
<div class="mb-4">
  <%= form_with model: event do |form| %>
    <%= render "shared/error_messages", form: form %>

    <div class="row form-row">
      <div class="form-group col-md-6">
        <%= form.label :start_date %>
        <%= form.date_field :start_date, class: "form-control mb-3"%>
      </div>
      <div class="form-group col-md-6">
        <%= form.label :end_date %>
        <%= form.date_field :end_date, class: "form-control mb-3" %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: "form-control mb-3", placeholder: :address %> 
    </div>

    <div class="row form-row">
      <div class="form-group">
        <%= form.label :theme %>
        <%= form.text_field :theme, class: "form-control mb-3", placeholder: :theme %> 
      </div>
    </div>

    <div class="form-group">
      <%= form.label :details %>
      <%= form.text_field :details, class: "form-control mb-3", placeholder: :details %> 
    </div>

    <div class="row form-row mb-3">
      <div class="form-group col-md-3">
        <%= form.label :time %>
        <%= form.time_field :time, class: "form-control mb-3" %>   
      </div>
      <div class="form-group col-md-3">
        <%= form.label :image %>
        <%= form.file_field :image, class: "form-control mb-3" %>
      </div>
      <div class="d-md-flex align-items-center justify-content-center form-group col-md-3 mb-3">
        <%= form.select :event_type, [["free", "free"], ["paid", "paid"]] %>
      </div>
      <div class="d-md-flex align-items-center justify-content-around form-group col-md-3 mb-3">
        <%= form.radio_button :status, "active" %>
        <%= form.label :active %>

        <%= form.radio_button :status, "inactive" %>
        <%= form.label :inacive, "inactive", class: "text-transform-capitalize" %>
      </div> 
    </div>
    <%= link_to "Cancel", events_path, class: "btn btn-primary py-1" %>
    <%= form.submit %>
  <% end %>
</div>

app/views/host/events/create.turbo_stream.erb
<%= turbo_stream.prepend "events" do %>
  <%= render partial: "host/events/event", locals: { event: @event }%>
<% end %>

<%= turbo_stream.update Event.new, "" %>
<%= turbo_stream.prepend "flash", partial: "shared/flash_messages"%>

app/views/host/events/destroy.turbo_stream.erb
<%= turbo_stream.remove @event %>
<%= turbo_stream.prepend "flash", partial: "shared/flash_messages" %>

app/views/host/events/details.html.erb
<%= turbo_frame_tag "show" do %>
  <div>
    <%= render partial: 'event_detail', locals: { event: @event } %>
    <div class="mx-auto detail-close" >
      <div>
        <%= link_to 'close', event_path(@event), style: "position: relative; bottom: 25px; left: 250px;" %>
      </div>   
    </div>
  </div>
<% end %>

app/views/host/events/edit.html.erb
<%= turbo_frame_tag dom_id(@event) do%>
  <%= render partial: 'form', locals: {event: @event}%>
<% end %>

app/views/host/events/index.html.erb
<%= turbo_stream_from "events" %>
<div class="mt-4">
  <%= @output %>

  <%= turbo_frame_tag Event.new %>

  <%= turbo_frame_tag "events" do %>
    <%= render "empty_state" %>
    <%= render @events %>
  <% end %>
</div>

app/views/host/events/new.html.erb
<%= turbo_frame_tag Event.new do%>
  <%= render partial: 'form', locals: { event: @event }%>
<% end %>

app/views/host/events/show.html.erb
<div class="row">
  <div class="">
    <div class="image-wrapper mx-auto mt-4 mb-2">
      <%= image_tag(@event.image, class: "author_image w-100") if @event.image %>
    </div>
   <%= turbo_frame_tag 'details' do %>
    <div class="mx-auto more">
      <div>
        <%= link_to 'more...', details_path(@event), data: { turbo_frame: "show" } %>
      </div>
    </div>
   <% end %>
  </div>
  <%= turbo_frame_tag 'show' %>
  <div style="" class="comments d-flex justify-content-center">
    <div style="width: 350px;">
      <% @comments.each do |comment| %>
        <div class="d-flex mb-2">
          <div class="comment-image-wrapper">
            <%= image_tag(comment.guest.avatar, size: "50") if comment.guest.avatar%>
          </div> 
          <div class="ms-2 d-flex align-items-end text-bottom"><%= comment.body %></div>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/host/events/update.turbo_stream.erb
<%= turbo_stream.replace @event %>
<%= turbo_stream.prepend "flash", partial: "shared/flash_messages" %>